version: 0
os: linux
files:
  - source: /wp
    destination: /home/ubuntu/app/wp
    overwrite: true
  - source: /nginx
    destination: /home/ubuntu/app/nginx
    overwrite: true
  - source: wp-cli.yml
    destination: /home/ubuntu/app
    overwrite: true
file_exists_behavior: OVERWRITE
permissions:
  - object: /home/ubuntu/app/wp
    owner: ubuntu
    group: ubuntu
  - object: /home/ubuntu/app/nginx
    owner: ubuntu
    group: ubuntu
  - object: /home/ubuntu/app/wp-cli.yml
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
    - location: scripts/predeploy.sh
      runas: ubuntu
  AfterInstall:
    - location: scripts/sso-conf.sh
      runas: ubuntu
    - location: scripts/deploy.sh
      runas: ubuntu
    - location: scripts/db-config.sh
      runas: ubuntu
    - location: scripts/composer.sh
      runas: ubuntu
    - location: scripts/postdeploy.sh
      runas: ubuntu
branch_config:
  wip\/.*: null
  staging:
    deploymentGroupName: staging-phila-gov
    deploymentGroupConfig:
      serviceRoleArn: 'arn:aws:iam::676612114792:role/beta.phila.gov_CodeDeploy'
    deploymentConfig:
      autoRollbackConfiguration:
        enabled: false
  test:
    deploymentGroupName: test-phila-gov
    deploymentGroupConfig:
      serviceRoleArn: 'arn:aws:iam::676612114792:role/beta.phila.gov_CodeDeploy'
    deploymentConfig:
      autoRollbackConfiguration:
        enabled: false
  main:
    deploymentGroupName: prod-phila-gov
    deploymentGroupConfig:
      serviceRoleArn: 'arn:aws:iam::676612114792:role/beta.phila.gov_CodeDeploy'
    deploymentConfig:
      autoRollbackConfiguration:
        enabled: false
