# .appspec.yml

# ... here be your existing CodeDeploy configuration.

# This section controls the action:

version: 0.0
os: linux

branch_config:
    wip\/.*: ~

    staging:
        deploymentGroupName: staging-phila-gov-codedeploy-deploymentgroup
        deploymentGroupConfig:
            serviceRoleArn: arn:aws:iam::676612114792:role/beta.phila.gov_CodeDeploy
        deploymentConfig:
            autoRollbackConfiguration:
                enabled: false

    test:
        deploymentGroupName: test-phila-gov
        deploymentGroupConfig:
            serviceRoleArn: arn:aws:iam::676612114792:role/beta.phila.gov_CodeDeploy
        deploymentConfig:
            autoRollbackConfiguration:
                enabled: false