version: 0.0
os: linux
files:
  - source: /wp
    destination: /home/ubuntu/app/wp
  - source: /nginx
    destination: /etc/nginx
permissions:
  - object: /home/ubuntu/app/
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
    - location: scripts/predeploy
      runas: ubuntu
  AfterInstall:
    - location: scripts/postdeploy
      runas: ubuntu
