#!/bin/bash

. .env

echo 'Loading database dump into instance database'
ssh -F .ssh/config $PHILA_INSTANCE 'mysql -uroot' <<EOF
DROP DATABASE IF EXISTS wp;
CREATE DATABASE wp;
EOF

aws s3 cp s3://$PHILA_DB_BUCKET/current.sql - | ssh -F .ssh/config $PHILA_INSTANCE 'mysql -uroot wp'
