#!/bin/bash

#set -x

# Pull in variables from .env
source .env

echo "Syncing environment variables."
ssh -F .ssh/config $PHILA_INSTANCE "cat > .ssh/environment" <<EOF
APP_ROOT=/home/ubuntu/phila.gov
WP_SITEURL=$WP_SITEURL
WP_HOME=$WP_HOME
AWS_ID=$AWS_ID
AWS_SECRET=$AWS_SECRET
S3_BUCKET=$S3_BUCKET
SWIFTYPE_ENGINE=$SWIFTYPE_ENGINE
COMPOSER_URL=$COMPOSER_URL
DB_NAME=$DB_NAME
DB_USER=$DB_USER
DB_PASS=$DB_PASS
DB_HOST=$DB_HOST
HTTPS=$HTTPS
ROBOTS_DISALLOW=$ROBOTS_DISALLOW
EOF

echo "Syncing files."
rsync -e 'ssh -F .ssh/config' -rzp --delete --exclude=".*" --delete-excluded ./ $PHILA_INSTANCE:phila.gov

echo "Running deploy script."
ssh -F .ssh/config $PHILA_INSTANCE 'cd phila.gov && scripts/deploy.sh'
