#!/bin/bash

. .env

[ ! "$PHILA_INSTANCE" ] && echo "No reference found for PHILA_INSTANCE." && exit 0

echo "Running deploy script."
ssh -F .ssh/config $PHILA_INSTANCE 'cd phila.gov && scripts/deploy.sh'
