#!/bin/bash

. lib/update_env
. .env

[ ! "$PHILA_INSTANCE" ] && echo "No reference found for PHILA_INSTANCE." && exit 0

read -p "Terminate instance $PHILA_INSTANCE? (Enter \"y\" to proceed.) " ref_replace
[ ! "$ref_replace" = "y" ] && exit 0

aws ec2 terminate-instances --instance-id=$PHILA_INSTANCE

update_env 'PHILA_INSTANCE' ''
