#!/bin/bash

. lib/update_env
. .env

if [ "$PHILA_INSTANCE" ]; then
  echo "Reference found: PHILA_INSTANCE=$PHILA_INSTANCE"
  read -p "Terminate instance? (Enter \"y\" to proceed.) " ref_replace
  [ ! "$ref_replace" = "y" ] && exit 0
else
  echo "No reference found for PHILA_INSTANCE."
  exit 1
fi

aws ec2 terminate-instances --instance-id=$PHILA_INSTANCE

update_env 'PHILA_INSTANCE' ''
