#!/bin/bash

. lib/update_env
. .env

echo "Waiting for instance $PHILA_INSTANCE to come online. This may take a few minutes."
while true; do
  sleep 5
  echo -n "."
  reachability=`aws ec2 describe-instance-status --instance-id=$PHILA_INSTANCE | grep reachability | head -n1 | cut -f3`
  [ "$reachability" = "passed" ] && break
done
echo

echo "Getting domain."
PHILA_DOMAIN=`aws ec2 describe-instances --instance-id=$PHILA_INSTANCE | grep '^INSTANCES' | cut -f14`

update_env 'PHILA_DOMAIN' $PHILA_DOMAIN

echo "Setting up ssh access."
mkdir -p .ssh
ssh-keyscan $PHILA_DOMAIN >> .ssh/known_hosts 2> /dev/null

cat >> .ssh/config <<EOF
Host $PHILA_INSTANCE
    User ubuntu
    HostName $PHILA_DOMAIN
    IdentityFile .ssh/$KEY_PAIR_NAME.pem
    UserKnownHostsFile .ssh/known_hosts
EOF

echo "Generating self-signed SSL certificate."
ssh -F .ssh/config $PHILA_INSTANCE "sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
  -keyout /etc/ssl/private/self-signed.key \
  -out /etc/ssl/certs/self-signed.crt \
  -subj \"/C=US/ST=Pennsylvania/L=Philadelphia/O=City of Philadelphia/OU=Office of Innovation and Technology/CN=$PHILA_DOMAIN\""

echo "Run instance/sync to begin syncing and deploying to https://$PHILA_DOMAIN."
