#!/bin/bash

. .env

[ ! "$PHILA_INSTANCE" ] && echo "No reference found for PHILA_INSTANCE." && exit 0

echo "Monitoring files and deploying on changes."
instance/deploy
fswatch -rdo -l5 --event Created --event Updated --event Removed . | while read num; do
  instance/deploy
done
