#!/bin/bash

export PATH="$PATH:/usr/local/bin"

source /home/ubuntu/app/environment

CFflush=1
aws s3 cp "s3://phila/deployments/${DEPLOYMENT_ID}" /home/ubuntu/deploycheck
if [ -f /home/ubuntu/deploycheck ]
then
  CFflush=0
  rm /home/ubuntu/deploycheck
else
  curl http://169.254.169.254/latest/meta-data/instance-id > /home/ubuntu/deploycheck
  aws s3 mv /home/ubuntu/deploycheck "s3://phila/deployments/${DEPLOYMENT_ID}"
fi

_dir="$(dirname "$0")"

echo 'Running grunt tasks'
cd /home/ubuntu/app/wp/wp-content/themes/phila.gov-theme
npm install
grunt

"$_dir/private-plugins.sh"

wp rewrite flush
wp core update-db
mkdir -p /home/ubuntu/app/wp/wp-content/uploads
chmod 777 -R /home/ubuntu/app/wp/wp-content/uploads

rm -rf /var/run/nginx-cache

if [ $CFflush -eq 1 ]
then
  sleep 10
  aws s3 cp "s3://phila/deployments/${DEPLOYMENT_ID}" /home/ubuntu/deploycheck
  if grep -q "$(curl http://169.254.169.254/latest/meta-data/instance-id)" /home/ubuntu/deploycheck
  then
    aws cloudfront create-invalidation --distribution-id E2KKF4LEAU9DV5 --paths /*
  fi
fi

rm /home/ubuntu/deploycheck

exit 0
