This email was sent from <?php echo $homeURL; ?>. 

We recently used Wordfence to audit the strength of passwords on our website.
We have detected that you have a weak password. 

This may mean that you have a password that is easy to guess. It may also mean that
you are using a password that is known to hackers.

Please sign into <?php echo $homeURL; ?> now and change your password to ensure
your account remains secure. You can access our sign-in page at:

<?php echo $loginURL; ?>


Your username is: <?php echo $username; ?>


We recommend that you use a pass-phrase or a combination of upper-case, lower-case, 
numbers and symbols in your password.

Thank you.

Email generated by Wordfence. Learn more at http://www.wordfence.com/zz4/
