This email was sent from <?php echo $homeURL; ?>. 

We recently used Wordfence to audit the strength of passwords on our website.
We have detected that you have a weak password. 

To ensure your user account remains secure we have changed your password to:

<?php echo $passwd; ?>

Please sign into <?php echo $homeURL; ?> now using this new password to verify
that it works. Your username is: <?php echo $username; ?>

We recommend that once you are signed-in you immediately change
this password to one of your own choosing. We suggest you use a pass-phrase or
a combination of upper-case, lower-case, numbers and symbols.

You can sign in here:

<?php echo $loginURL; ?>

Thank you.

Email generated by Wordfence. Learn more at http://www.wordfence.com/zz3/
