name: Prod deploy announcement
on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        
    - name: MS Teams Card
      uses: toko-bifrost/ms-teams-deploy-card@master
      with:
        github-token: ${{ github.token }}
        webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        card-layout-start: cozy
