name: Deploy to prod 2
on:
  push:
    branches:
      - prod-2

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - uses: actions/checkout@v2
      - id: prod-2-deploy
        uses: webfactory/create-aws-codedeploy-deployment@v0.3.0
        with: 
          application: prod-2-phila-gov